name: Psycholog Dominika Pluskiewicz | Terapia CBT Wroc≈Çaw
author: Dominika Pluskiewicz
plugins_dir:
  - jekyll-sitemap
  - jekyll-copyr
exclude:
  - bower_components
jekyll-copyr:
  tasks:
    - from: "./bower_components/."
      to: "./_site/bower_components/"
